version: '3.8'

services:
  web:
    build: .
    command: bash -c "
      sleep 5 &&
      pip install --no-cache-dir -e . &&
      alembic upgrade head &&
      python scripts/create-initial-data.py &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=genem
      - POSTGRES_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=genem
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 