version: '3.8'

services:
  web:
    build: .
    command: bash -c "
      pip install --no-cache-dir -e . &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development

